# Generated by Django 5.2.6 on 2025-09-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_model',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_name',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='millage',
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
